var ogSites = [
    {
        urlRegex: 'avclub.com',
        selector: '.item, article.short, article > .heading',
    },
    {
        urlRegex: 'buzzfeed.com',
        selector:
            '.card--article-featured, .card--article, .card--package, .card--video, .sidebar__link, .js-now-buzzing__list > li',
    },
    {
        urlRegex: 'facebook.com',
        selector:
            'div[data-testid="fbfeed_story"], div[role="article"], #pagelet_trending_tags_and_topics ul > li',
    },
    {
        urlRegex: 'feedly.com',
        selector: '.entry',
    },
    {
        urlRegex: 'gizmodo.com',
        selector: '.featured-item, article',
    },
    {
        urlRegex: 'news.google.com',
        selector: 'a[target="_blank"]',
    },
    {
        urlRegex: 'plus.google.com',
        selector: 'div[id^="update-"], c-wiz div div c-wiz',
    },
    {
        urlRegex: 'reddit.com',
        selector: '.sitetable > .thing.link, .usertext-body, .scrollerItem',
    },
    {
        urlRegex: 'slack.com',
        selector: 'ts-message',
    },
    {
        urlRegex: 'tumblr.com',
        selector: '.post_container, article',
    },
    {
        urlRegex: 'twitter.com',
        selector: "[data-item-type='tweet'], .trend-item",
    },
    {
        urlRegex: 'youtube.com',
        selector: '.yt-lockup, .related-list-item, .comment-renderer-text',
    },
];

var ogSpoilers = [
    {spoiler: '#got', isRegex: false},
    {spoiler: 'ady stonehea', isRegex: false},
    {spoiler: 'aidan gillen', isRegex: false},
    {spoiler: 'alfie allen', isRegex: false},
    {spoiler: 'arya stark', isRegex: false},
    {spoiler: 'asoiaf', isRegex: false},
    {spoiler: 'azor ahai', isRegex: false},
    {spoiler: 'baelish', isRegex: false},
    {spoiler: 'baratheon', isRegex: false},
    {spoiler: 'ben crompton', isRegex: false},
    {spoiler: 'bloodraven', isRegex: false},
    {spoiler: 'braavos', isRegex: false},
    {spoiler: 'bran stark', isRegex: false},
    {spoiler: 'briene of tarth', isRegex: false},
    {spoiler: 'brienne of tarth', isRegex: false},
    {spoiler: 'carice van houten', isRegex: false},
    {spoiler: 'casterly rock', isRegex: false},
    {spoiler: 'cersei ', isRegex: false},
    {spoiler: 'conleth hill', isRegex: false},
    {spoiler: 'd.b. weiss', isRegex: false},
    {spoiler: 'daenerys', isRegex: false},
    {spoiler: 'daniel portman', isRegex: false},
    {spoiler: 'david benioff', isRegex: false},
    {spoiler: 'davos seaworth', isRegex: false},
    {spoiler: 'dornish', isRegex: false},
    {spoiler: 'dothraki', isRegex: false},
    {spoiler: 'dreadfort', isRegex: false},
    {spoiler: 'emilia clarke', isRegex: false},
    {spoiler: 'game of thrones', isRegex: false},
    {spoiler: 'gameofthrone', isRegex: false},
    {spoiler: 'gameofthone', isRegex: false},
    {spoiler: 'gamesofthrone', isRegex: false},
    {spoiler: 'greyjoy', isRegex: false},
    {spoiler: 'gwendoline christie', isRegex: false},
    {spoiler: 'highgarden', isRegex: false},
    {spoiler: 'hodor', isRegex: false},
    {spoiler: 'house bolton', isRegex: false},
    {spoiler: 'house stark', isRegex: false},
    {spoiler: 'house tyrell', isRegex: false},
    {spoiler: 'howland reed', isRegex: false},
    {spoiler: 'iain glen', isRegex: false},
    {spoiler: 'ian mcelhinney', isRegex: false},
    {spoiler: 'iron throne', isRegex: false},
    {spoiler: 'isaac hempstead wright', isRegex: false},
    {spoiler: 'jerome flynn', isRegex: false},
    {spoiler: 'john bradley', isRegex: false},
    {spoiler: 'jojen reed', isRegex: false},
    {spoiler: 'jon snow', isRegex: false},
    {spoiler: 'julian glover', isRegex: false},
    {spoiler: 'khaleesi', isRegex: false},
    {spoiler: "king's landing", isRegex: false},
    {spoiler: 'kit harington', isRegex: false},
    {spoiler: 'kit harrington', isRegex: false},
    {spoiler: 'kristian nairn', isRegex: false},
    {spoiler: 'lanister', isRegex: false},
    {spoiler: 'lannisport', isRegex: false},
    {spoiler: 'lannister', isRegex: false},
    {spoiler: 'lena headey', isRegex: false},
    {spoiler: 'liam cunningham', isRegex: false},
    {spoiler: 'littlefinger', isRegex: false},
    {spoiler: 'maisie williams', isRegex: false},
    {spoiler: 'meereen', isRegex: false},
    {spoiler: 'melisandre', isRegex: false},
    {spoiler: 'michele fairley', isRegex: false},
    {spoiler: 'michelle fairley', isRegex: false},
    {spoiler: 'myrcella', isRegex: false},
    {spoiler: 'natalie dormer', isRegex: false},
    {spoiler: 'nathalie emmanue', isRegex: false},
    {spoiler: 'ned stark', isRegex: false},
    {spoiler: 'nikolaj coster-waldau', isRegex: false},
    {spoiler: 'olenna tyrell', isRegex: false},
    {spoiler: 'peter dinklage', isRegex: false},
    {spoiler: 'podrick payne', isRegex: false},
    {spoiler: 'queen of thorns', isRegex: false},
    {spoiler: 'ramsay bolton', isRegex: false},
    {spoiler: 'roose bolton', isRegex: false},
    {spoiler: 'rory mccann', isRegex: false},
    {spoiler: 'sandor clegane', isRegex: false},
    {spoiler: 'sansa stark', isRegex: false},
    {spoiler: 'sophie turner', isRegex: false},
    {spoiler: 'sothoryos', isRegex: false},
    {spoiler: 'stephen dillane', isRegex: false},
    {spoiler: 'targaryen', isRegex: false},
    {spoiler: 'three eyed raven', isRegex: false},
    {spoiler: 'tower of joy', isRegex: false},
    {spoiler: 'tyrion', isRegex: false},
    {spoiler: 'vaes dothrak', isRegex: false},
    {spoiler: 'viserys', isRegex: false},
    {spoiler: 'walder frey', isRegex: false},
    {spoiler: 'westeros', isRegex: false},
    {spoiler: 'white walker', isRegex: false},
    {spoiler: 'whitewalker', isRegex: false},
    {spoiler: 'wildling', isRegex: false},
    {spoiler: 'winterfell', isRegex: false},
];

var ogIgnoredSubreddits = [
    'gameofthrones',
    'asoiaf',
    'iceandfire',
    'agotboardgame',
    'gamesofthrones',
    'westeros',
    'thronescomics',
    'asongofmemesandrage',
    'earthoficeandfire',
];

var settings = {
    sites: ogSites,
    spoilers: ogSpoilers,
};

export default settings;
